# Generated by Django 3.2.6 on 2021-09-11 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField()),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer_id', models.IntegerField()),
                ('fuel', models.CharField(max_length=10)),
                ('vehicle_segment', models.CharField(max_length=5)),
                ('premium_amount', models.IntegerField()),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('customer_gender', models.BooleanField(default=False)),
                ('income_group', models.CharField(max_length=20)),
                ('customer_region', models.CharField(max_length=10)),
                ('maritial_status', models.BooleanField(default=False)),
            ],
        ),
    ]
